import { CaptionStyles } from "../types";

export const captionTemplates: Record<
  string,
  { name: string; styles: CaptionStyles; preview: string; isPro?: boolean }
> = {
  classic: {
    name: "Classic",
    preview: "Clean & Professional",
    styles: {
      fontFamily: "Inter, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      textShadow: "2px 2px 4px rgba(0,0,0,0.6), 0 0 20px rgba(0,0,0,0.3)",
      padding: "12px",
      fontWeight: 500,
      letterSpacing: "0.01em",
      highlightStyle: {
        backgroundColor: "rgba(59, 130, 246, 0.92)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        textShadow: "2px 2px 4px rgba(0,0,0,0.4)",
        borderRadius: "6px",
        padding: "2px 8px",
      },
    },
  },
  hustle: {
    name: "Hustle",
    preview: "Bold & Dynamic",
    isPro: true,
    styles: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 800,
      letterSpacing: "-0.02em",
      textShadow: "3px 3px 0 rgba(0,0,0,0.8)",
      highlightStyle: {
        backgroundColor: "#FF3B3B",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 800,
        textShadow: "3px 3px 0 rgba(0,0,0,0.8)",
        borderRadius: "2px",
        padding: "4px 12px",
      },
    },
  },
  medusa: {
    name: "Medusa",
    preview: "Modern & Sleek",
    isPro: true,
    styles: {
      fontFamily: "Space Grotesk, sans-serif",
      fontSize: "2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 500,
      letterSpacing: "0.02em",
      highlightStyle: {
        backgroundColor: "rgba(34, 197, 94, 0.95)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        borderRadius: "8px",
        padding: "4px 12px",
      },
    },
  },
  minimal: {
    name: "Minimal",
    preview: "Simple & Clean",
    styles: {
      fontFamily: "Inter, sans-serif",
      fontSize: "1.5rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FFFFFF",
      backgroundColor: "rgba(0,0,0,0.6)",
      padding: "4px 22px",
      highlightStyle: {
        backgroundColor: "rgba(0,0,0,0.8)",
        color: "#FFFFFF",
        scale: 1.02,
        fontWeight: 500,
        padding: "2px 8px",
        borderRadius: "4px",
      },
    },
  },
  neon: {
    name: "Neon",
    preview: "Vibrant & Electric",
    isPro: true,
    styles: {
      fontFamily: "Outfit, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      textShadow: "0 0 10px rgba(255,255,255,0.9), 0 0 20px rgba(255,255,255,0.5), 0 0 30px rgba(255,255,255,0.3)",
      highlightStyle: {
        backgroundColor: "rgba(139, 92, 246, 0.25)",
        color: "#F0ABFC",
        scale: 1.07,
        fontWeight: 600,
        textShadow: "0 0 10px rgba(240,171,252,0.9), 0 0 20px rgba(240,171,252,0.5), 0 0 30px rgba(240,171,252,0.3)",
        borderRadius: "8px",
        padding: "4px 16px",
      },
    },
  },
  handwritten: {
    name: "Handwritten",
    preview: "Casual & Friendly",
    styles: {
      fontFamily: "Caveat, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      textShadow: "1px 1px 2px rgba(0,0,0,0.6)",
      fontWeight: "normal",
      padding: "8px",
      highlightStyle: {
        backgroundColor: "rgba(34, 197, 94, 0.9)",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 600,
        textShadow: "1px 1px 2px rgba(0,0,0,0.4)",
        borderRadius: "8px",
      },
    },
  },
  retro: {
    name: "Retro",
    preview: "Vintage & Bold",
    isPro: true,
    styles: {
      fontFamily: "Rubik Mono One, sans-serif",
      fontSize: "1.8rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FFD700",
      textShadow: "3px 3px 0 #FF4500",
      letterSpacing: "0.02em",
      highlightStyle: {
        backgroundColor: "#FF4500",
        color: "#FFD700",
        scale: 1.05,
        fontWeight: 400,
        textShadow: "2px 2px 0 #000000",
        borderRadius: "0px",
        padding: "2px 8px",
      },
    },
  },
  cinematic: {
    name: "Cinematic",
    preview: "Dramatic & Bold",
    isPro: true,
    styles: {
      fontFamily: "Playfair Display, serif",
      fontSize: "2.4rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 700,
      letterSpacing: "0.03em",
      textShadow: "2px 2px 8px rgba(0,0,0,0.6)",
      highlightStyle: {
        backgroundColor: "rgba(245, 158, 11, 0.9)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 700,
        textShadow: "2px 2px 8px rgba(0,0,0,0.6)",
        borderRadius: "2px",
        padding: "4px 16px",
      },
    },
  },
  gradient: {
    name: "Gradient",
    preview: "Smooth & Modern",
    isPro: true,
    styles: {
      fontFamily: "Plus Jakarta Sans, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 600,
      background: "linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0))",
      backdropFilter: "blur(8px)",
      padding: "12px 24px",
      borderRadius: "12px",
      textShadow: "2px 2px 4px rgba(0,0,0,0.3)",
      highlightStyle: {
        backgroundColor: "black",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 700,
        textShadow: "1px 1px 2px rgba(0,0,0,0.2)",
        borderRadius: "8px",
        padding: "4px 16px",
      },
    },
  },
  future: {
    name: "Future",
    preview: "Sci-fi & Techy",
    isPro: true,
    styles: {
      fontFamily: "Space Grotesk, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#E2E8F0",
      fontWeight: 600,
      letterSpacing: "0.02em",
      textShadow: "0 0 15px rgba(148,163,184,0.5)",
      padding: "12px",
      highlightStyle: {
        backgroundColor: "rgba(14,165,233,0.15)",
        color: "#38BDF8",
        scale: 1.06,
        fontWeight: 700,
        textShadow: "0 0 15px rgba(56,189,248,0.6)",
        borderRadius: "4px",
        padding: "4px 16px",
        border: "1px solid rgba(56,189,248,0.3)",
        backdropFilter: "blur(4px)",
      },
    },
  },
  elegant: {
    name: "Elegant",
    preview: "Sophisticated & Refined",
    styles: {
      fontFamily: "Cormorant Garamond, serif",
      fontSize: "2.3rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#F8F9FA",
      fontWeight: 400,
      letterSpacing: "0.01em",
      textShadow: "1px 1px 3px rgba(0,0,0,0.5)",
      highlightStyle: {
        backgroundColor: "rgba(168, 85, 247, 0.9)",
        color: "#FFFFFF",
        scale: 1.04,
        fontWeight: 500,
        borderRadius: "6px",
        padding: "3px 10px",
      },
    },
  },
  comic: {
    name: "Comic",
    preview: "Fun & Playful",
    styles: {
      fontFamily: "Comic Neue, cursive",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FBBF24",
      fontWeight: 700,
      textShadow: "2px 2px 0 #000000, 4px 4px 0 rgba(0,0,0,0.3)",
      highlightStyle: {
        backgroundColor: "#F59E0B",
        color: "#FFFFFF",
        scale: 1.1,
        fontWeight: 800,
        textShadow: "2px 2px 0 #000000",
        borderRadius: "12px",
        padding: "4px 12px",
      },
    },
  },
  typewriter: {
    name: "Typewriter",
    preview: "Vintage & Literary",
    isPro: true,
    styles: {
      fontFamily: "Courier New, monospace",
      fontSize: "1.9rem",
      lineHeight: 1.4,
      textAlign: "left",
      color: "#E5E7EB",
      fontWeight: 400,
      letterSpacing: "0.05em",
      backgroundColor: "rgba(0,0,0,0.7)",
      padding: "16px 20px",
      borderRadius: "4px",
      highlightStyle: {
        backgroundColor: "#DC2626",
        color: "#FFFFFF",
        scale: 1.02,
        fontWeight: 600,
        borderRadius: "2px",
        padding: "2px 6px",
      },
    },
  },
  glow: {
    name: "Glow",
    preview: "Luminous & Ethereal",
    isPro: true,
    styles: {
      fontFamily: "Poppins, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 500,
      textShadow: "0 0 20px rgba(255,255,255,0.8), 0 0 40px rgba(255,255,255,0.4)",
      highlightStyle: {
        backgroundColor: "rgba(59, 130, 246, 0.2)",
        color: "#60A5FA",
        scale: 1.06,
        fontWeight: 600,
        textShadow: "0 0 20px rgba(96,165,250,0.9), 0 0 40px rgba(96,165,250,0.5)",
        borderRadius: "8px",
        padding: "4px 14px",
      },
    },
  },
  shadow: {
    name: "Shadow",
    preview: "Deep & Mysterious",
    styles: {
      fontFamily: "Inter, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 600,
      textShadow: "4px 4px 8px rgba(0,0,0,0.8), 2px 2px 4px rgba(0,0,0,0.6)",
      highlightStyle: {
        backgroundColor: "rgba(17, 24, 39, 0.9)",
        color: "#F3F4F6",
        scale: 1.05,
        fontWeight: 700,
        textShadow: "2px 2px 4px rgba(0,0,0,0.8)",
        borderRadius: "6px",
        padding: "4px 12px",
      },
    },
  },
  outline: {
    name: "Outline",
    preview: "Bold & Striking",
    styles: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "2.3rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "transparent",
      fontWeight: 800,
      textShadow: "2px 2px 4px rgba(0,0,0,0.5)",
      highlightStyle: {
        backgroundColor: "#EF4444",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 800,
        borderRadius: "4px",
        padding: "4px 12px",
      },
    },
  },
  luxury: {
    name: "Luxury",
    preview: "Premium & Exclusive",
    isPro: true,
    styles: {
      fontFamily: "Playfair Display, serif",
      fontSize: "2.4rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FCD34D",
      fontWeight: 600,
      letterSpacing: "0.02em",
      textShadow: "2px 2px 4px rgba(0,0,0,0.6), 0 0 20px rgba(252,211,77,0.3)",
      highlightStyle: {
        backgroundColor: "rgba(217, 119, 6, 0.9)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 700,
        borderRadius: "8px",
        padding: "4px 16px",
      },
    },
  },
  tech: {
    name: "Tech",
    preview: "Digital & Modern",
    isPro: true,
    styles: {
      fontFamily: "JetBrains Mono, monospace",
      fontSize: "1.9rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#10B981",
      fontWeight: 500,
      letterSpacing: "0.03em",
      textShadow: "0 0 10px rgba(16,185,129,0.5)",
      backgroundColor: "rgba(0,0,0,0.8)",
      padding: "12px 16px",
      borderRadius: "6px",
      highlightStyle: {
        backgroundColor: "#059669",
        color: "#FFFFFF",
        scale: 1.04,
        fontWeight: 600,
        borderRadius: "4px",
        padding: "2px 8px",
      },
    },
  },
  vintage: {
    name: "Vintage",
    preview: "Classic & Timeless",
    styles: {
      fontFamily: "Crimson Text, serif",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#F4F3F0",
      fontWeight: 400,
      letterSpacing: "0.01em",
      textShadow: "2px 2px 4px rgba(101,67,33,0.8)",
      backgroundColor: "rgba(101,67,33,0.2)",
      padding: "16px 20px",
      borderRadius: "8px",
      highlightStyle: {
        backgroundColor: "#92400E",
        color: "#FEF3C7",
        scale: 1.03,
        fontWeight: 600,
        borderRadius: "4px",
        padding: "3px 10px",
      },
    },
  },
  modern: {
    name: "Modern",
    preview: "Contemporary & Fresh",
    styles: {
      fontFamily: "Inter, sans-serif",
      fontSize: "2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 500,
      letterSpacing: "0.01em",
      textShadow: "1px 1px 3px rgba(0,0,0,0.4)",
      highlightStyle: {
        backgroundColor: "rgba(99, 102, 241, 0.9)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 600,
        borderRadius: "6px",
        padding: "3px 10px",
      },
    },
  },
  bold: {
    name: "Bold",
    preview: "Strong & Impactful",
    styles: {
      fontFamily: "Oswald, sans-serif",
      fontSize: "2.5rem",
      lineHeight: 1.1,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 700,
      letterSpacing: "0.02em",
      textShadow: "3px 3px 6px rgba(0,0,0,0.8)",
      highlightStyle: {
        backgroundColor: "#DC2626",
        color: "#FFFFFF",
        scale: 1.1,
        fontWeight: 800,
        borderRadius: "4px",
        padding: "4px 14px",
      },
    },
  },
  soft: {
    name: "Soft",
    preview: "Gentle & Subtle",
    styles: {
      fontFamily: "Nunito, sans-serif",
      fontSize: "2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#F8FAFC",
      fontWeight: 400,
      letterSpacing: "0.005em",
      textShadow: "1px 1px 2px rgba(0,0,0,0.3)",
      backgroundColor: "rgba(255,255,255,0.1)",
      padding: "12px 18px",
      borderRadius: "12px",
      backdropFilter: "blur(4px)",
      highlightStyle: {
        backgroundColor: "rgba(168, 85, 247, 0.8)",
        color: "#FFFFFF",
        scale: 1.03,
        fontWeight: 500,
        borderRadius: "8px",
        padding: "3px 10px",
      },
    },
  },
  urban: {
    name: "Urban",
    preview: "Street & Edgy",
    isPro: true,
    styles: {
      fontFamily: "Bebas Neue, sans-serif",
      fontSize: "2.4rem",
      lineHeight: 1.1,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      letterSpacing: "0.05em",
      textShadow: "2px 2px 0 #000000, 4px 4px 0 rgba(0,0,0,0.5)",
      highlightStyle: {
        backgroundColor: "#F59E0B",
        color: "#000000",
        scale: 1.08,
        fontWeight: 400,
        textShadow: "1px 1px 0 #FFFFFF",
        borderRadius: "2px",
        padding: "4px 12px",
      },
    },
  },
  dreamy: {
    name: "Dreamy",
    preview: "Soft & Ethereal",
    isPro: true,
    styles: {
      fontFamily: "Dancing Script, cursive",
      fontSize: "2.3rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#F0ABFC",
      fontWeight: 500,
      letterSpacing: "0.01em",
      textShadow: "0 0 15px rgba(240,171,252,0.6), 2px 2px 4px rgba(0,0,0,0.3)",
      highlightStyle: {
        backgroundColor: "rgba(168, 85, 247, 0.3)",
        color: "#FBBF24",
        scale: 1.06,
        fontWeight: 600,
        textShadow: "0 0 15px rgba(251,191,36,0.8)",
        borderRadius: "12px",
        padding: "4px 14px",
      },
    },
  },
  corporate: {
    name: "Corporate",
    preview: "Professional & Clean",
    styles: {
      fontFamily: "Source Sans Pro, sans-serif",
      fontSize: "2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#1F2937",
      fontWeight: 600,
      letterSpacing: "0.01em",
      backgroundColor: "rgba(255,255,255,0.95)",
      padding: "14px 20px",
      borderRadius: "8px",
      textShadow: "none",
      highlightStyle: {
        backgroundColor: "#3B82F6",
        color: "#FFFFFF",
        scale: 1.02,
        fontWeight: 700,
        borderRadius: "4px",
        padding: "2px 8px",
      },
    },
  },
  artistic: {
    name: "Artistic",
    preview: "Creative & Expressive",
    isPro: true,
    styles: {
      fontFamily: "Abril Fatface, serif",
      fontSize: "2.3rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      letterSpacing: "0.02em",
      textShadow: "3px 3px 0 #EC4899, 6px 6px 0 #8B5CF6",
      highlightStyle: {
        backgroundColor: "rgba(236, 72, 153, 0.9)",
        color: "#FFFFFF",
        scale: 1.07,
        fontWeight: 400,
        textShadow: "2px 2px 0 #8B5CF6",
        borderRadius: "6px",
        padding: "4px 12px",
      },
    },
  },
  gaming: {
    name: "Gaming",
    preview: "Dynamic & Energetic",
    isPro: true,
    styles: {
      fontFamily: "Orbitron, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#00FF88",
      fontWeight: 700,
      letterSpacing: "0.03em",
      textShadow: "0 0 10px rgba(0,255,136,0.8), 2px 2px 4px rgba(0,0,0,0.6)",
      highlightStyle: {
        backgroundColor: "rgba(0, 255, 136, 0.2)",
        color: "#FF0080",
        scale: 1.08,
        fontWeight: 800,
        textShadow: "0 0 10px rgba(255,0,128,0.8)",
        borderRadius: "4px",
        padding: "4px 12px",
        border: "1px solid rgba(255,0,128,0.5)",
      },
    },
  },
  newspaper: {
    name: "Newspaper",
    preview: "Editorial & Formal",
    styles: {
      fontFamily: "Times New Roman, serif",
      fontSize: "1.9rem",
      lineHeight: 1.4,
      textAlign: "left",
      color: "#1F2937",
      fontWeight: 400,
      letterSpacing: "0.005em",
      backgroundColor: "rgba(255,255,255,0.9)",
      padding: "16px 20px",
      borderRadius: "4px",
      textShadow: "none",
      highlightStyle: {
        backgroundColor: "#1F2937",
        color: "#FFFFFF",
        scale: 1.01,
        fontWeight: 600,
        borderRadius: "2px",
        padding: "1px 6px",
      },
    },
  },
  cyberpunk: {
    name: "Cyberpunk",
    preview: "Futuristic & Neon",
    isPro: true,
    styles: {
      fontFamily: "Rajdhani, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#00FFFF",
      fontWeight: 600,
      letterSpacing: "0.04em",
      textShadow: "0 0 10px rgba(0,255,255,0.8), 0 0 20px rgba(0,255,255,0.4), 2px 2px 4px rgba(0,0,0,0.8)",
      backgroundColor: "rgba(0,0,0,0.8)",
      padding: "12px 16px",
      borderRadius: "2px",
      highlightStyle: {
        backgroundColor: "#FF0080",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 700,
        textShadow: "0 0 10px rgba(255,0,128,0.8)",
        borderRadius: "2px",
        padding: "3px 10px",
      },
    },
  },
  romantic: {
    name: "Romantic",
    preview: "Elegant & Loving",
    styles: {
      fontFamily: "Great Vibes, cursive",
      fontSize: "2.4rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#F8BBD9",
      fontWeight: 400,
      letterSpacing: "0.01em",
      textShadow: "2px 2px 4px rgba(0,0,0,0.4), 0 0 15px rgba(248,187,217,0.4)",
      highlightStyle: {
        backgroundColor: "rgba(236, 72, 153, 0.8)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 400,
        borderRadius: "12px",
        padding: "4px 14px",
      },
    },
  },
  horror: {
    name: "Horror",
    preview: "Dark & Spooky",
    isPro: true,
    styles: {
      fontFamily: "Creepster, cursive",
      fontSize: "2.1rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#DC2626",
      fontWeight: 400,
      letterSpacing: "0.02em",
      textShadow: "3px 3px 0 #000000, 0 0 20px rgba(220,38,38,0.6)",
      backgroundColor: "rgba(0,0,0,0.9)",
      padding: "14px 18px",
      borderRadius: "8px",
      highlightStyle: {
        backgroundColor: "#7F1D1D",
        color: "#FEF2F2",
        scale: 1.08,
        fontWeight: 400,
        textShadow: "2px 2px 0 #000000",
        borderRadius: "4px",
        padding: "4px 12px",
      },
    },
  },
  motivational: {
    name: "Motivational",
    preview: "Inspiring & Uplifting",
    styles: {
      fontFamily: "Raleway, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 600,
      letterSpacing: "0.02em",
      textShadow: "2px 2px 4px rgba(0,0,0,0.6)",
      highlightStyle: {
        backgroundColor: "rgba(34, 197, 94, 0.9)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 700,
        borderRadius: "6px",
        padding: "4px 12px",
      },
    },
  },
  casual: {
    name: "Casual",
    preview: "Relaxed & Friendly",
    styles: {
      fontFamily: "Open Sans, sans-serif",
      fontSize: "2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#374151",
      fontWeight: 400,
      letterSpacing: "0.005em",
      backgroundColor: "rgba(255,255,255,0.9)",
      padding: "12px 16px",
      borderRadius: "8px",
      textShadow: "none",
      highlightStyle: {
        backgroundColor: "#F59E0B",
        color: "#FFFFFF",
        scale: 1.03,
        fontWeight: 600,
        borderRadius: "6px",
        padding: "3px 10px",
      },
    },
  },
  festive: {
    name: "Festive",
    preview: "Celebratory & Joyful",
    styles: {
      fontFamily: "Fredoka One, cursive",
      fontSize: "2.3rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FBBF24",
      fontWeight: 400,
      letterSpacing: "0.01em",
      textShadow: "3px 3px 0 #DC2626, 6px 6px 0 #059669",
      highlightStyle: {
        backgroundColor: "#DC2626",
        color: "#FBBF24",
        scale: 1.1,
        fontWeight: 400,
        textShadow: "2px 2px 0 #059669",
        borderRadius: "8px",
        padding: "4px 14px",
      },
    },
  },
  professional: {
    name: "Professional",
    preview: "Business & Formal",
    styles: {
      fontFamily: "Lato, sans-serif",
      fontSize: "2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#1F2937",
      fontWeight: 500,
      letterSpacing: "0.01em",
      backgroundColor: "rgba(249,250,251,0.95)",
      padding: "14px 20px",
      borderRadius: "6px",
      textShadow: "none",
      highlightStyle: {
        backgroundColor: "#1F2937",
        color: "#FFFFFF",
        scale: 1.02,
        fontWeight: 600,
        borderRadius: "4px",
        padding: "2px 8px",
      },
    },
  },
  adventure: {
    name: "Adventure",
    preview: "Exciting & Bold",
    isPro: true,
    styles: {
      fontFamily: "Bangers, cursive",
      fontSize: "2.4rem",
      lineHeight: 1.1,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      letterSpacing: "0.03em",
      textShadow: "3px 3px 0 #DC2626, 6px 6px 0 #000000",
      highlightStyle: {
        backgroundColor: "#DC2626",
        color: "#FBBF24",
        scale: 1.1,
        fontWeight: 400,
        textShadow: "2px 2px 0 #000000",
        borderRadius: "4px",
        padding: "4px 14px",
      },
    },
  },
  zen: {
    name: "Zen",
    preview: "Peaceful & Calm",
    styles: {
      fontFamily: "Noto Serif, serif",
      fontSize: "2rem",
      lineHeight: 1.5,
      textAlign: "center",
      color: "#6B7280",
      fontWeight: 300,
      letterSpacing: "0.02em",
      backgroundColor: "rgba(255,255,255,0.8)",
      padding: "16px 24px",
      borderRadius: "12px",
      textShadow: "none",
      highlightStyle: {
        backgroundColor: "rgba(34, 197, 94, 0.8)",
        color: "#FFFFFF",
        scale: 1.02,
        fontWeight: 400,
        borderRadius: "8px",
        padding: "3px 10px",
      },
    },
  },
  party: {
    name: "Party",
    preview: "Fun & Vibrant",
    styles: {
      fontFamily: "Righteous, cursive",
      fontSize: "2.3rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      letterSpacing: "0.02em",
      textShadow: "2px 2px 0 #EC4899, 4px 4px 0 #8B5CF6, 6px 6px 0 #F59E0B",
      highlightStyle: {
        backgroundColor: "#EC4899",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 400,
        textShadow: "2px 2px 0 #8B5CF6",
        borderRadius: "12px",
        padding: "4px 14px",
      },
    },
  },
  academic: {
    name: "Academic",
    preview: "Scholarly & Refined",
    styles: {
      fontFamily: "Libre Baskerville, serif",
      fontSize: "1.9rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#1F2937",
      fontWeight: 400,
      letterSpacing: "0.005em",
      backgroundColor: "rgba(255,255,255,0.9)",
      padding: "16px 20px",
      borderRadius: "4px",
      textShadow: "none",
      highlightStyle: {
        backgroundColor: "#3B82F6",
        color: "#FFFFFF",
        scale: 1.01,
        fontWeight: 500,
        borderRadius: "3px",
        padding: "2px 8px",
      },
    },
  },
  sports: {
    name: "Sports",
    preview: "Athletic & Dynamic",
    isPro: true,
    styles: {
      fontFamily: "Anton, sans-serif",
      fontSize: "2.5rem",
      lineHeight: 1.1,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      letterSpacing: "0.04em",
      textShadow: "3px 3px 0 #000000, 6px 6px 0 rgba(0,0,0,0.5)",
      highlightStyle: {
        backgroundColor: "#EF4444",
        color: "#FFFFFF",
        scale: 1.12,
        fontWeight: 400,
        textShadow: "2px 2px 0 #000000",
        borderRadius: "2px",
        padding: "4px 16px",
      },
    },
  },
  nature: {
    name: "Nature",
    preview: "Organic & Fresh",
    styles: {
      fontFamily: "Merriweather, serif",
      fontSize: "2.1rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#065F46",
      fontWeight: 400,
      letterSpacing: "0.01em",
      backgroundColor: "rgba(236,253,245,0.9)",
      padding: "14px 18px",
      borderRadius: "12px",
      textShadow: "none",
      highlightStyle: {
        backgroundColor: "#059669",
        color: "#FFFFFF",
        scale: 1.03,
        fontWeight: 500,
        borderRadius: "8px",
        padding: "3px 10px",
      },
    },
  },
  space: {
    name: "Space",
    preview: "Cosmic & Mysterious",
    isPro: true,
    styles: {
      fontFamily: "Exo 2, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#A78BFA",
      fontWeight: 500,
      letterSpacing: "0.03em",
      textShadow: "0 0 15px rgba(167,139,250,0.6), 2px 2px 4px rgba(0,0,0,0.8)",
      backgroundColor: "rgba(17,24,39,0.9)",
      padding: "14px 18px",
      borderRadius: "8px",
      highlightStyle: {
        backgroundColor: "rgba(139, 92, 246, 0.8)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        textShadow: "0 0 10px rgba(255,255,255,0.5)",
        borderRadius: "6px",
        padding: "4px 12px",
      },
    },
  },
  retro_wave: {
    name: "Retro Wave",
    preview: "80s & Synthwave",
    isPro: true,
    styles: {
      fontFamily: "Orbitron, sans-serif",
      fontSize: "2.3rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FF0080",
      fontWeight: 700,
      letterSpacing: "0.04em",
      textShadow: "0 0 10px rgba(255,0,128,0.8), 0 0 20px rgba(255,0,128,0.4), 3px 3px 0 #00FFFF",
      highlightStyle: {
        backgroundColor: "rgba(0, 255, 255, 0.2)",
        color: "#00FFFF",
        scale: 1.08,
        fontWeight: 800,
        textShadow: "0 0 10px rgba(0,255,255,0.8), 2px 2px 0 #FF0080",
        borderRadius: "4px",
        padding: "4px 14px",
        border: "1px solid rgba(0,255,255,0.5)",
      },
    },
  },
  watercolor: {
    name: "Watercolor",
    preview: "Artistic & Flowing",
    isPro: true,
    styles: {
      fontFamily: "Kalam, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#7C3AED",
      fontWeight: 400,
      letterSpacing: "0.01em",
      textShadow: "1px 1px 3px rgba(124,58,237,0.3), 0 0 15px rgba(124,58,237,0.2)",
      backgroundColor: "rgba(255,255,255,0.7)",
      padding: "14px 20px",
      borderRadius: "16px",
      highlightStyle: {
        backgroundColor: "rgba(236, 72, 153, 0.7)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 500,
        borderRadius: "12px",
        padding: "4px 12px",
      },
    },
  },
  minimalist: {
    name: "Minimalist",
    preview: "Ultra Clean & Simple",
    styles: {
      fontFamily: "Work Sans, sans-serif",
      fontSize: "1.8rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#374151",
      fontWeight: 300,
      letterSpacing: "0.02em",
      backgroundColor: "rgba(255,255,255,0.95)",
      padding: "12px 20px",
      borderRadius: "2px",
      textShadow: "none",
      highlightStyle: {
        backgroundColor: "#6B7280",
        color: "#FFFFFF",
        scale: 1.01,
        fontWeight: 400,
        borderRadius: "1px",
        padding: "1px 6px",
      },
    },
  },
  grunge: {
    name: "Grunge",
    preview: "Raw & Edgy",
    isPro: true,
    styles: {
      fontFamily: "Special Elite, cursive",
      fontSize: "2.1rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#F3F4F6",
      fontWeight: 400,
      letterSpacing: "0.02em",
      textShadow: "2px 2px 4px rgba(0,0,0,0.8), 0 0 10px rgba(243,244,246,0.3)",
      backgroundColor: "rgba(31,41,55,0.8)",
      padding: "14px 18px",
      borderRadius: "4px",
      highlightStyle: {
        backgroundColor: "#DC2626",
        color: "#F9FAFB",
        scale: 1.05,
        fontWeight: 400,
        textShadow: "1px 1px 2px rgba(0,0,0,0.8)",
        borderRadius: "2px",
        padding: "3px 10px",
      },
    },
  },
}
