import type { CaptionStyles } from "../types"

export const captionTemplates: Record<
  string,
  { name: string; styles: CaptionStyles; preview: string; isPro?: boolean }
> = {
  classic: {
    name: "Classic",
    preview: "Clean & Professional",
    styles: {
      fontFamily: "Inter, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      textShadow: "2px 2px 4px rgba(0,0,0,0.6), 0 0 20px rgba(0,0,0,0.3)",
      padding: "12px",
      fontWeight: 500,
      letterSpacing: "0.01em",
      highlightStyle: {
        backgroundColor: "rgba(59, 130, 246, 0.92)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        textShadow: "2px 2px 4px rgba(0,0,0,0.4)",
        borderRadius: "6px",
        padding: "2px 8px",
      },
    },
  },
  hustle: {
    name: "Hustle",
    preview: "Bold & Dynamic",
    isPro: true,
    styles: {
      fontFamily: "Montserrat, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 800,
      letterSpacing: "-0.02em",
      textShadow: "3px 3px 0 rgba(0,0,0,0.8)",
      highlightStyle: {
        backgroundColor: "#FF3B3B",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 800,
        textShadow: "3px 3px 0 rgba(0,0,0,0.8)",
        borderRadius: "2px",
        padding: "4px 12px",
      },
    },
  },
  medusa: {
    name: "Medusa",
    preview: "Modern & Sleek",
    isPro: true,
    styles: {
      fontFamily: "Space Grotesk, sans-serif",
      fontSize: "2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 500,
      letterSpacing: "0.02em",
      highlightStyle: {
        backgroundColor: "rgba(34, 197, 94, 0.95)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        borderRadius: "8px",
        padding: "4px 12px",
      },
    },
  },
  minimal: {
    name: "Minimal",
    preview: "Simple & Clean",
    styles: {
      fontFamily: "Inter, sans-serif",
      fontSize: "1.5rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FFFFFF",
      backgroundColor: "rgba(0,0,0,0.6)",
      padding: "4px 22px",
      highlightStyle: {
        backgroundColor: "rgba(0,0,0,0.8)",
        color: "#FFFFFF",
        scale: 1.02,
        fontWeight: 500,
        padding: "2px 8px",
        borderRadius: "4px",
      },
    },
  },
  neon: {
    name: "Neon",
    preview: "Vibrant & Electric",
    isPro: true,
    styles: {
      fontFamily: "Outfit, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      textShadow: "0 0 10px rgba(255,255,255,0.9), 0 0 20px rgba(255,255,255,0.5), 0 0 30px rgba(255,255,255,0.3)",
      highlightStyle: {
        backgroundColor: "rgba(139, 92, 246, 0.25)",
        color: "#F0ABFC",
        scale: 1.07,
        fontWeight: 600,
        textShadow: "0 0 10px rgba(240,171,252,0.9), 0 0 20px rgba(240,171,252,0.5), 0 0 30px rgba(240,171,252,0.3)",
        borderRadius: "8px",
        padding: "4px 16px",
      },
    },
  },
  handwritten: {
    name: "Handwritten",
    preview: "Casual & Friendly",
    styles: {
      fontFamily: "Caveat, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      textShadow: "1px 1px 2px rgba(0,0,0,0.6)",
      fontWeight: "normal",
      padding: "8px",
      highlightStyle: {
        backgroundColor: "rgba(34, 197, 94, 0.9)",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 600,
        textShadow: "1px 1px 2px rgba(0,0,0,0.4)",
        borderRadius: "8px",
      },
    },
  },
  retro: {
    name: "Retro",
    preview: "Vintage & Bold",
    isPro: true,
    styles: {
      fontFamily: "Rubik Mono One, sans-serif",
      fontSize: "1.8rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FFD700",
      textShadow: "3px 3px 0 #FF4500",
      letterSpacing: "0.02em",
      highlightStyle: {
        backgroundColor: "#FF4500",
        color: "#FFD700",
        scale: 1.05,
        fontWeight: 400,
        textShadow: "2px 2px 0 #000000",
        borderRadius: "0px",
        padding: "2px 8px",
      },
    },
  },
  cinematic: {
    name: "Cinematic",
    preview: "Dramatic & Bold",
    isPro: true,
    styles: {
      fontFamily: "Playfair Display, serif",
      fontSize: "2.4rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 700,
      letterSpacing: "0.03em",
      textShadow: "2px 2px 8px rgba(0,0,0,0.6)",
      highlightStyle: {
        backgroundColor: "rgba(245, 158, 11, 0.9)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 700,
        textShadow: "2px 2px 8px rgba(0,0,0,0.6)",
        borderRadius: "2px",
        padding: "4px 16px",
      },
    },
  },
  gradient: {
    name: "Gradient",
    preview: "Smooth & Modern",
    isPro: true,
    styles: {
      fontFamily: "Plus Jakarta Sans, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 600,
      background: "linear-gradient(135deg, rgba(255,255,255,0.1), rgba(255,255,255,0))",
      backdropFilter: "blur(8px)",
      padding: "12px 24px",
      borderRadius: "12px",
      textShadow: "2px 2px 4px rgba(0,0,0,0.3)",
      highlightStyle: {
        backgroundColor: "black",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 700,
        textShadow: "1px 1px 2px rgba(0,0,0,0.2)",
        borderRadius: "8px",
        padding: "4px 16px",
      },
    },
  },
  future: {
    name: "Future",
    preview: "Sci-fi & Techy",
    isPro: true,
    styles: {
      fontFamily: "Space Grotesk, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#E2E8F0",
      fontWeight: 600,
      letterSpacing: "0.02em",
      textShadow: "0 0 15px rgba(148,163,184,0.5)",
      padding: "12px",
      highlightStyle: {
        backgroundColor: "rgba(14,165,233,0.15)",
        color: "#38BDF8",
        scale: 1.06,
        fontWeight: 700,
        textShadow: "0 0 15px rgba(56,189,248,0.6)",
        borderRadius: "4px",
        padding: "4px 16px",
        border: "1px solid rgba(56,189,248,0.3)",
        backdropFilter: "blur(4px)",
      },
    },
  },
  elegant: {
    name: "Elegant",
    preview: "Sophisticated & Refined",
    isPro: true,
    styles: {
      fontFamily: "Cormorant Garamond, serif",
      fontSize: "2.3rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#F8F9FA",
      fontWeight: 400,
      letterSpacing: "0.05em",
      textShadow: "1px 1px 3px rgba(0,0,0,0.4)",
      highlightStyle: {
        backgroundColor: "rgba(168, 85, 247, 0.85)",
        color: "#FFFFFF",
        scale: 1.04,
        fontWeight: 500,
        fontStyle: "italic",
        borderRadius: "12px",
        padding: "6px 18px",
      },
    },
  },
  comic: {
    name: "Comic",
    preview: "Fun & Playful",
    styles: {
      fontFamily: "Comic Neue, cursive",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 700,
      textShadow: "3px 3px 0 #000000, -1px -1px 0 #000000, 1px -1px 0 #000000, -1px 1px 0 #000000",
      highlightStyle: {
        backgroundColor: "#FBBF24",
        color: "#000000",
        scale: 1.08,
        fontWeight: 800,
        textShadow: "2px 2px 0 #FFFFFF",
        borderRadius: "16px",
        padding: "4px 14px",
      },
    },
  },
  typewriter: {
    name: "Typewriter",
    preview: "Vintage & Mechanical",
    isPro: true,
    styles: {
      fontFamily: "Courier Prime, monospace",
      fontSize: "2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#E5E7EB",
      fontWeight: 400,
      letterSpacing: "0.1em",
      backgroundColor: "rgba(0,0,0,0.8)",
      padding: "16px 24px",
      borderRadius: "4px",
      highlightStyle: {
        backgroundColor: "#DC2626",
        color: "#FFFFFF",
        scale: 1.03,
        fontWeight: 700,
        padding: "2px 8px",
        borderRadius: "2px",
      },
    },
  },
  graffiti: {
    name: "Graffiti",
    preview: "Urban & Edgy",
    isPro: true,
    styles: {
      fontFamily: "Permanent Marker, cursive",
      fontSize: "2.4rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      textShadow: "4px 4px 0 #000000, 8px 8px 0 rgba(0,0,0,0.3)",
      transform: "rotate(-2deg)",
      highlightStyle: {
        backgroundColor: "#EF4444",
        color: "#FFFF00",
        scale: 1.1,
        fontWeight: 400,
        textShadow: "3px 3px 0 #000000",
        borderRadius: "0px",
        padding: "6px 16px",
        transform: "rotate(1deg)",
      },
    },
  },
  luxury: {
    name: "Luxury",
    preview: "Premium & Exclusive",
    isPro: true,
    styles: {
      fontFamily: "Playfair Display, serif",
      fontSize: "2.5rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#D4AF37",
      fontWeight: 400,
      letterSpacing: "0.08em",
      textShadow: "2px 2px 4px rgba(0,0,0,0.8)",
      highlightStyle: {
        backgroundColor: "rgba(212, 175, 55, 0.2)",
        color: "#FFD700",
        scale: 1.05,
        fontWeight: 600,
        textShadow: "2px 2px 6px rgba(0,0,0,0.6)",
        borderRadius: "8px",
        padding: "8px 20px",
        border: "2px solid rgba(212, 175, 55, 0.5)",
      },
    },
  },
  cyberpunk: {
    name: "Cyberpunk",
    preview: "Futuristic & Glitchy",
    isPro: true,
    styles: {
      fontFamily: "Orbitron, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#00FFFF",
      fontWeight: 700,
      letterSpacing: "0.05em",
      textShadow: "0 0 10px #00FFFF, 0 0 20px #00FFFF, 0 0 30px #00FFFF",
      highlightStyle: {
        backgroundColor: "rgba(255, 0, 255, 0.3)",
        color: "#FF00FF",
        scale: 1.06,
        fontWeight: 800,
        textShadow: "0 0 10px #FF00FF, 0 0 20px #FF00FF",
        borderRadius: "2px",
        padding: "4px 12px",
        border: "1px solid #FF00FF",
      },
    },
  },
  vintage: {
    name: "Vintage",
    preview: "Classic & Timeless",
    styles: {
      fontFamily: "Libre Baskerville, serif",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#F5F5DC",
      fontWeight: 400,
      letterSpacing: "0.02em",
      textShadow: "2px 2px 4px rgba(101, 67, 33, 0.8)",
      backgroundColor: "rgba(101, 67, 33, 0.6)",
      padding: "12px 20px",
      borderRadius: "8px",
      highlightStyle: {
        backgroundColor: "#8B4513",
        color: "#F5F5DC",
        scale: 1.04,
        fontWeight: 600,
        padding: "4px 12px",
        borderRadius: "4px",
      },
    },
  },
  neonPink: {
    name: "Neon Pink",
    preview: "Bright & Electric",
    isPro: true,
    styles: {
      fontFamily: "Exo 2, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FF1493",
      fontWeight: 600,
      textShadow: "0 0 15px #FF1493, 0 0 30px #FF1493, 0 0 45px #FF1493",
      highlightStyle: {
        backgroundColor: "rgba(255, 20, 147, 0.2)",
        color: "#FFFFFF",
        scale: 1.07,
        fontWeight: 700,
        textShadow: "0 0 20px #FFFFFF, 0 0 40px #FFFFFF",
        borderRadius: "12px",
        padding: "6px 16px",
        border: "2px solid #FF1493",
      },
    },
  },
  sketch: {
    name: "Sketch",
    preview: "Hand-drawn & Artistic",
    styles: {
      fontFamily: "Kalam, cursive",
      fontSize: "2.1rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#374151",
      fontWeight: 400,
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      padding: "12px 18px",
      borderRadius: "12px",
      border: "3px solid #374151",
      highlightStyle: {
        backgroundColor: "#FBBF24",
        color: "#374151",
        scale: 1.05,
        fontWeight: 700,
        borderRadius: "8px",
        padding: "4px 12px",
        border: "2px solid #374151",
      },
    },
  },
  matrix: {
    name: "Matrix",
    preview: "Digital & Code-like",
    isPro: true,
    styles: {
      fontFamily: "Source Code Pro, monospace",
      fontSize: "1.9rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#00FF00",
      fontWeight: 500,
      letterSpacing: "0.05em",
      textShadow: "0 0 10px #00FF00, 0 0 20px #00FF00",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      padding: "10px 16px",
      borderRadius: "4px",
      highlightStyle: {
        backgroundColor: "rgba(0, 255, 0, 0.2)",
        color: "#00FF00",
        scale: 1.04,
        fontWeight: 700,
        textShadow: "0 0 15px #00FF00",
        borderRadius: "2px",
        padding: "2px 8px",
        border: "1px solid #00FF00",
      },
    },
  },
  watercolor: {
    name: "Watercolor",
    preview: "Soft & Artistic",
    isPro: true,
    styles: {
      fontFamily: "Dancing Script, cursive",
      fontSize: "2.4rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 600,
      textShadow: "1px 1px 3px rgba(0,0,0,0.3)",
      background: "linear-gradient(45deg, rgba(168, 85, 247, 0.6), rgba(236, 72, 153, 0.6), rgba(59, 130, 246, 0.6))",
      padding: "16px 24px",
      borderRadius: "20px",
      highlightStyle: {
        backgroundColor: "rgba(255, 255, 255, 0.3)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 700,
        borderRadius: "12px",
        padding: "6px 16px",
        backdropFilter: "blur(4px)",
      },
    },
  },
  bold3d: {
    name: "Bold 3D",
    preview: "Dimensional & Strong",
    isPro: true,
    styles: {
      fontFamily: "Fredoka One, cursive",
      fontSize: "2.3rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      textShadow: "4px 4px 0 #000000, 8px 8px 0 rgba(0,0,0,0.5)",
      highlightStyle: {
        backgroundColor: "#F59E0B",
        color: "#FFFFFF",
        scale: 1.08,
        fontWeight: 400,
        textShadow: "3px 3px 0 #000000, 6px 6px 0 rgba(0,0,0,0.3)",
        borderRadius: "8px",
        padding: "6px 16px",
      },
    },
  },
  newspaper: {
    name: "Newspaper",
    preview: "Editorial & Classic",
    styles: {
      fontFamily: "Merriweather, serif",
      fontSize: "2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#1F2937",
      fontWeight: 700,
      backgroundColor: "rgba(255, 255, 255, 0.95)",
      padding: "16px 24px",
      borderRadius: "4px",
      border: "2px solid #1F2937",
      highlightStyle: {
        backgroundColor: "#1F2937",
        color: "#FFFFFF",
        scale: 1.03,
        fontWeight: 700,
        borderRadius: "2px",
        padding: "4px 12px",
      },
    },
  },
  hologram: {
    name: "Hologram",
    preview: "Translucent & Futuristic",
    isPro: true,
    styles: {
      fontFamily: "Rajdhani, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#7DD3FC",
      fontWeight: 500,
      letterSpacing: "0.03em",
      textShadow: "0 0 20px rgba(125, 211, 252, 0.8)",
      backgroundColor: "rgba(125, 211, 252, 0.1)",
      padding: "12px 20px",
      borderRadius: "8px",
      border: "1px solid rgba(125, 211, 252, 0.3)",
      backdropFilter: "blur(8px)",
      highlightStyle: {
        backgroundColor: "rgba(125, 211, 252, 0.2)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 600,
        textShadow: "0 0 25px rgba(255, 255, 255, 0.8)",
        borderRadius: "6px",
        padding: "4px 14px",
        border: "1px solid rgba(255, 255, 255, 0.4)",
      },
    },
  },
  chalkboard: {
    name: "Chalkboard",
    preview: "Educational & Rustic",
    styles: {
      fontFamily: "Architects Daughter, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      backgroundColor: "rgba(34, 34, 34, 0.9)",
      padding: "16px 24px",
      borderRadius: "8px",
      textShadow: "1px 1px 2px rgba(255,255,255,0.3)",
      highlightStyle: {
        backgroundColor: "#FBBF24",
        color: "#1F2937",
        scale: 1.04,
        fontWeight: 600,
        borderRadius: "6px",
        padding: "4px 12px",
      },
    },
  },
  gothic: {
    name: "Gothic",
    preview: "Dark & Mysterious",
    isPro: true,
    styles: {
      fontFamily: "Cinzel, serif",
      fontSize: "2.3rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#DC143C",
      fontWeight: 600,
      letterSpacing: "0.05em",
      textShadow: "3px 3px 6px rgba(0,0,0,0.8)",
      backgroundColor: "rgba(0, 0, 0, 0.7)",
      padding: "14px 22px",
      borderRadius: "4px",
      highlightStyle: {
        backgroundColor: "#8B0000",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 700,
        textShadow: "2px 2px 4px rgba(0,0,0,0.6)",
        borderRadius: "2px",
        padding: "6px 16px",
      },
    },
  },
  bubble: {
    name: "Bubble",
    preview: "Soft & Rounded",
    styles: {
      fontFamily: "Nunito, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 600,
      backgroundColor: "rgba(59, 130, 246, 0.8)",
      padding: "16px 28px",
      borderRadius: "50px",
      textShadow: "1px 1px 3px rgba(0,0,0,0.3)",
      highlightStyle: {
        backgroundColor: "#FFFFFF",
        color: "#3B82F6",
        scale: 1.06,
        fontWeight: 700,
        borderRadius: "25px",
        padding: "6px 18px",
      },
    },
  },
  stencil: {
    name: "Stencil",
    preview: "Military & Industrial",
    isPro: true,
    styles: {
      fontFamily: "Oswald, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#000000",
      fontWeight: 700,
      letterSpacing: "0.1em",
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      padding: "12px 20px",
      borderRadius: "2px",
      textTransform: "uppercase",
      highlightStyle: {
        backgroundColor: "#DC2626",
        color: "#FFFFFF",
        scale: 1.04,
        fontWeight: 800,
        borderRadius: "0px",
        padding: "4px 12px",
      },
    },
  },
  rainbow: {
    name: "Rainbow",
    preview: "Colorful & Vibrant",
    isPro: true,
    styles: {
      fontFamily: "Righteous, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      background: "linear-gradient(45deg, #FF0000, #FF7F00, #FFFF00, #00FF00, #0000FF, #4B0082, #9400D3)",
      backgroundClip: "text",
      WebkitBackgroundClip: "text",
      WebkitTextFillColor: "transparent",
      textShadow: "2px 2px 4px rgba(0,0,0,0.5)",
      highlightStyle: {
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        color: "#FFFFFF",
        scale: 1.07,
        fontWeight: 600,
        borderRadius: "12px",
        padding: "6px 16px",
      },
    },
  },
  pixelated: {
    name: "Pixelated",
    preview: "Retro Gaming",
    styles: {
      fontFamily: "Press Start 2P, cursive",
      fontSize: "1.6rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#00FF00",
      fontWeight: 400,
      backgroundColor: "rgba(0, 0, 0, 0.9)",
      padding: "12px 16px",
      borderRadius: "0px",
      textShadow: "2px 2px 0 #000000",
      highlightStyle: {
        backgroundColor: "#FFFF00",
        color: "#000000",
        scale: 1.05,
        fontWeight: 400,
        borderRadius: "0px",
        padding: "4px 8px",
      },
    },
  },
  marble: {
    name: "Marble",
    preview: "Elegant & Textured",
    isPro: true,
    styles: {
      fontFamily: "Crimson Text, serif",
      fontSize: "2.4rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#2D3748",
      fontWeight: 600,
      letterSpacing: "0.03em",
      backgroundColor: "rgba(247, 250, 252, 0.95)",
      padding: "18px 26px",
      borderRadius: "12px",
      textShadow: "1px 1px 2px rgba(0,0,0,0.1)",
      highlightStyle: {
        backgroundColor: "#4A5568",
        color: "#FFFFFF",
        scale: 1.04,
        fontWeight: 700,
        borderRadius: "8px",
        padding: "6px 16px",
      },
    },
  },
  fire: {
    name: "Fire",
    preview: "Hot & Intense",
    isPro: true,
    styles: {
      fontFamily: "Bungee, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#FF4500",
      fontWeight: 400,
      textShadow: "0 0 10px #FF4500, 0 0 20px #FF6347, 0 0 30px #FFD700",
      highlightStyle: {
        backgroundColor: "rgba(255, 69, 0, 0.3)",
        color: "#FFFF00",
        scale: 1.08,
        fontWeight: 400,
        textShadow: "0 0 15px #FFFF00, 0 0 30px #FF4500",
        borderRadius: "8px",
        padding: "6px 16px",
      },
    },
  },
  ice: {
    name: "Ice",
    preview: "Cool & Crystalline",
    isPro: true,
    styles: {
      fontFamily: "Quicksand, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#E0F2FE",
      fontWeight: 500,
      letterSpacing: "0.02em",
      textShadow: "0 0 15px rgba(224, 242, 254, 0.8), 0 0 30px rgba(186, 230, 253, 0.6)",
      backgroundColor: "rgba(7, 89, 133, 0.3)",
      padding: "14px 22px",
      borderRadius: "12px",
      backdropFilter: "blur(6px)",
      highlightStyle: {
        backgroundColor: "rgba(224, 242, 254, 0.2)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 600,
        textShadow: "0 0 20px rgba(255, 255, 255, 0.9)",
        borderRadius: "8px",
        padding: "4px 14px",
        border: "1px solid rgba(224, 242, 254, 0.4)",
      },
    },
  },
  metallic: {
    name: "Metallic",
    preview: "Shiny & Industrial",
    isPro: true,
    styles: {
      fontFamily: "Roboto Condensed, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#C0C0C0",
      fontWeight: 700,
      letterSpacing: "0.05em",
      textShadow: "2px 2px 4px rgba(0,0,0,0.6), 0 0 10px rgba(192,192,192,0.5)",
      backgroundColor: "rgba(64, 64, 64, 0.8)",
      padding: "12px 20px",
      borderRadius: "4px",
      highlightStyle: {
        backgroundColor: "#FFD700",
        color: "#000000",
        scale: 1.05,
        fontWeight: 800,
        textShadow: "1px 1px 2px rgba(0,0,0,0.3)",
        borderRadius: "2px",
        padding: "4px 14px",
      },
    },
  },
  organic: {
    name: "Organic",
    preview: "Natural & Flowing",
    styles: {
      fontFamily: "Amatic SC, cursive",
      fontSize: "2.5rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#22C55E",
      fontWeight: 700,
      textShadow: "2px 2px 4px rgba(0,0,0,0.4)",
      backgroundColor: "rgba(255, 255, 255, 0.9)",
      padding: "16px 24px",
      borderRadius: "25px",
      highlightStyle: {
        backgroundColor: "#16A34A",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 700,
        borderRadius: "20px",
        padding: "6px 18px",
      },
    },
  },
  glitch: {
    name: "Glitch",
    preview: "Distorted & Digital",
    isPro: true,
    styles: {
      fontFamily: "JetBrains Mono, monospace",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#FF0080",
      fontWeight: 600,
      letterSpacing: "0.02em",
      textShadow: "2px 0 #00FFFF, -2px 0 #FFFF00",
      highlightStyle: {
        backgroundColor: "rgba(0, 0, 0, 0.8)",
        color: "#00FF00",
        scale: 1.06,
        fontWeight: 700,
        textShadow: "1px 0 #FF0080, -1px 0 #00FFFF",
        borderRadius: "2px",
        padding: "4px 12px",
      },
    },
  },
  royal: {
    name: "Royal",
    preview: "Majestic & Regal",
    isPro: true,
    styles: {
      fontFamily: "Cinzel Decorative, cursive",
      fontSize: "2.4rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#9333EA",
      fontWeight: 600,
      letterSpacing: "0.08em",
      textShadow: "3px 3px 6px rgba(0,0,0,0.5)",
      backgroundColor: "rgba(255, 255, 255, 0.95)",
      padding: "18px 28px",
      borderRadius: "16px",
      border: "3px solid #9333EA",
      highlightStyle: {
        backgroundColor: "#9333EA",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 700,
        borderRadius: "12px",
        padding: "8px 20px",
      },
    },
  },
  neonGreen: {
    name: "Neon Green",
    preview: "Electric & Vibrant",
    isPro: true,
    styles: {
      fontFamily: "Audiowide, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#39FF14",
      fontWeight: 400,
      textShadow: "0 0 15px #39FF14, 0 0 30px #39FF14, 0 0 45px #39FF14",
      backgroundColor: "rgba(0, 0, 0, 0.8)",
      padding: "12px 20px",
      borderRadius: "8px",
      highlightStyle: {
        backgroundColor: "rgba(57, 255, 20, 0.2)",
        color: "#FFFFFF",
        scale: 1.07,
        fontWeight: 600,
        textShadow: "0 0 20px #FFFFFF, 0 0 40px #39FF14",
        borderRadius: "6px",
        padding: "6px 16px",
        border: "2px solid #39FF14",
      },
    },
  },
  steampunk: {
    name: "Steampunk",
    preview: "Victorian & Mechanical",
    isPro: true,
    styles: {
      fontFamily: "Uncial Antiqua, cursive",
      fontSize: "2.3rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#CD853F",
      fontWeight: 400,
      letterSpacing: "0.03em",
      textShadow: "2px 2px 4px rgba(0,0,0,0.6)",
      backgroundColor: "rgba(139, 69, 19, 0.8)",
      padding: "16px 24px",
      borderRadius: "8px",
      border: "2px solid #CD853F",
      highlightStyle: {
        backgroundColor: "#B8860B",
        color: "#FFFFFF",
        scale: 1.04,
        fontWeight: 600,
        borderRadius: "4px",
        padding: "6px 16px",
      },
    },
  },
  space: {
    name: "Space",
    preview: "Cosmic & Infinite",
    isPro: true,
    styles: {
      fontFamily: "Orbitron, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#E6E6FA",
      fontWeight: 500,
      letterSpacing: "0.05em",
      textShadow: "0 0 20px rgba(230, 230, 250, 0.8), 0 0 40px rgba(138, 43, 226, 0.6)",
      background: "linear-gradient(135deg, rgba(25, 25, 112, 0.8), rgba(72, 61, 139, 0.8))",
      padding: "14px 22px",
      borderRadius: "12px",
      highlightStyle: {
        backgroundColor: "rgba(138, 43, 226, 0.3)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        textShadow: "0 0 25px rgba(255, 255, 255, 0.9)",
        borderRadius: "8px",
        padding: "6px 16px",
        border: "1px solid rgba(230, 230, 250, 0.5)",
      },
    },
  },
  ocean: {
    name: "Ocean",
    preview: "Deep & Flowing",
    styles: {
      fontFamily: "Merriweather Sans, sans-serif",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 500,
      textShadow: "2px 2px 6px rgba(0,0,0,0.5)",
      background: "linear-gradient(135deg, rgba(59, 130, 246, 0.8), rgba(14, 165, 233, 0.8), rgba(6, 182, 212, 0.8))",
      padding: "16px 24px",
      borderRadius: "16px",
      highlightStyle: {
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 600,
        borderRadius: "12px",
        padding: "6px 18px",
        backdropFilter: "blur(4px)",
      },
    },
  },
  desert: {
    name: "Desert",
    preview: "Warm & Sandy",
    styles: {
      fontFamily: "Sahitya, serif",
      fontSize: "2.3rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#8B4513",
      fontWeight: 600,
      letterSpacing: "0.02em",
      backgroundColor: "rgba(255, 228, 181, 0.9)",
      padding: "16px 24px",
      borderRadius: "12px",
      textShadow: "1px 1px 3px rgba(0,0,0,0.2)",
      highlightStyle: {
        backgroundColor: "#D2691E",
        color: "#FFFFFF",
        scale: 1.04,
        fontWeight: 700,
        borderRadius: "8px",
        padding: "6px 16px",
      },
    },
  },
  forest: {
    name: "Forest",
    preview: "Natural & Earthy",
    styles: {
      fontFamily: "Lora, serif",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 500,
      textShadow: "2px 2px 4px rgba(0,0,0,0.6)",
      background: "linear-gradient(135deg, rgba(34, 197, 94, 0.8), rgba(22, 163, 74, 0.8), rgba(21, 128, 61, 0.8))",
      padding: "16px 24px",
      borderRadius: "20px",
      highlightStyle: {
        backgroundColor: "rgba(255, 255, 255, 0.25)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 600,
        borderRadius: "15px",
        padding: "6px 18px",
        backdropFilter: "blur(3px)",
      },
    },
  },
  sunset: {
    name: "Sunset",
    preview: "Warm & Romantic",
    isPro: true,
    styles: {
      fontFamily: "Satisfy, cursive",
      fontSize: "2.4rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 400,
      textShadow: "2px 2px 6px rgba(0,0,0,0.4)",
      background: "linear-gradient(135deg, rgba(251, 146, 60, 0.8), rgba(249, 115, 22, 0.8), rgba(239, 68, 68, 0.8))",
      padding: "18px 26px",
      borderRadius: "25px",
      highlightStyle: {
        backgroundColor: "rgba(255, 255, 255, 0.3)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        borderRadius: "20px",
        padding: "8px 20px",
        backdropFilter: "blur(4px)",
      },
    },
  },
  storm: {
    name: "Storm",
    preview: "Dramatic & Powerful",
    isPro: true,
    styles: {
      fontFamily: "Bebas Neue, cursive",
      fontSize: "2.4rem",
      lineHeight: 1.2,
      textAlign: "center",
      color: "#E5E7EB",
      fontWeight: 400,
      letterSpacing: "0.05em",
      textShadow: "3px 3px 6px rgba(0,0,0,0.8), 0 0 20px rgba(255,255,255,0.3)",
      backgroundColor: "rgba(55, 65, 81, 0.9)",
      padding: "14px 22px",
      borderRadius: "6px",
      highlightStyle: {
        backgroundColor: "#FBBF24",
        color: "#1F2937",
        scale: 1.06,
        fontWeight: 400,
        textShadow: "2px 2px 4px rgba(0,0,0,0.3)",
        borderRadius: "3px",
        padding: "6px 16px",
      },
    },
  },
  crystal: {
    name: "Crystal",
    preview: "Clear & Prismatic",
    isPro: true,
    styles: {
      fontFamily: "Poppins, sans-serif",
      fontSize: "2.1rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#F8FAFC",
      fontWeight: 500,
      letterSpacing: "0.03em",
      textShadow: "0 0 15px rgba(248, 250, 252, 0.8), 0 0 30px rgba(203, 213, 225, 0.6)",
      backgroundColor: "rgba(148, 163, 184, 0.2)",
      padding: "14px 22px",
      borderRadius: "12px",
      backdropFilter: "blur(10px)",
      border: "1px solid rgba(248, 250, 252, 0.3)",
      highlightStyle: {
        backgroundColor: "rgba(248, 250, 252, 0.3)",
        color: "#FFFFFF",
        scale: 1.05,
        fontWeight: 600,
        textShadow: "0 0 20px rgba(255, 255, 255, 0.9)",
        borderRadius: "8px",
        padding: "4px 14px",
        border: "1px solid rgba(255, 255, 255, 0.4)",
        backdropFilter: "blur(6px)",
      },
    },
  },
  shadow: {
    name: "Shadow",
    preview: "Mysterious & Deep",
    isPro: true,
    styles: {
      fontFamily: "Creepster, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.3,
      textAlign: "center",
      color: "#6B7280",
      fontWeight: 400,
      letterSpacing: "0.02em",
      textShadow: "4px 4px 8px rgba(0,0,0,0.9), 0 0 20px rgba(107, 114, 128, 0.5)",
      backgroundColor: "rgba(17, 24, 39, 0.9)",
      padding: "16px 24px",
      borderRadius: "8px",
      highlightStyle: {
        backgroundColor: "rgba(107, 114, 128, 0.3)",
        color: "#F9FAFB",
        scale: 1.05,
        fontWeight: 600,
        textShadow: "2px 2px 6px rgba(0,0,0,0.8)",
        borderRadius: "6px",
        padding: "6px 16px",
      },
    },
  },
  aurora: {
    name: "Aurora",
    preview: "Ethereal & Magical",
    isPro: true,
    styles: {
      fontFamily: "Comfortaa, cursive",
      fontSize: "2.2rem",
      lineHeight: 1.4,
      textAlign: "center",
      color: "#FFFFFF",
      fontWeight: 500,
      textShadow: "0 0 20px rgba(255, 255, 255, 0.8), 0 0 40px rgba(168, 85, 247, 0.6)",
      background:
        "linear-gradient(135deg, rgba(168, 85, 247, 0.3), rgba(59, 130, 246, 0.3), rgba(34, 197, 94, 0.3), rgba(236, 72, 153, 0.3))",
      padding: "16px 24px",
      borderRadius: "20px",
      backdropFilter: "blur(8px)",
      highlightStyle: {
        backgroundColor: "rgba(255, 255, 255, 0.2)",
        color: "#FFFFFF",
        scale: 1.06,
        fontWeight: 600,
        textShadow: "0 0 25px rgba(255, 255, 255, 0.9)",
        borderRadius: "15px",
        padding: "6px 18px",
        backdropFilter: "blur(6px)",
      },
    },
  },
}
